---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: anyapplication-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: https://host.docker.internal:19443/validate-dcp-hiro-io-v1-anyapplication
  failurePolicy: Fail
  name: vanyapplication-v1.kb.io
  rules:
  - apiGroups:
    - dcp.hiro.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - anyapplications
  sideEffects: None
